# Generated by Django 5.2.4 on 2025-07-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('data_nascimento', models.DateField(verbose_name='dataNascimento')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='uf')),
                ('pais', models.CharField(max_length=100, verbose_name='pais')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('nome_usuario', models.CharField(max_length=50, unique=True, verbose_name='usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
            ],
        ),
    ]
