# Generated by Django 5.2.4 on 2025-07-31 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='dataNascimento')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=40, null=True, verbose_name='uf')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='pais')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
